// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSummaryHandlerFunc turns a function with the right signature into a get summary handler
type GetSummaryHandlerFunc func(GetSummaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSummaryHandlerFunc) Handle(params GetSummaryParams) middleware.Responder {
	return fn(params)
}

// GetSummaryHandler interface for that can handle valid get summary params
type GetSummaryHandler interface {
	Handle(GetSummaryParams) middleware.Responder
}

// NewGetSummary creates a new http.Handler for the get summary operation
func NewGetSummary(ctx *middleware.Context, handler GetSummaryHandler) *GetSummary {
	return &GetSummary{Context: ctx, Handler: handler}
}

/*
	GetSummary swagger:route GET /summary getSummary

GetSummary get summary API
*/
type GetSummary struct {
	Context *middleware.Context
	Handler GetSummaryHandler
}

func (o *GetSummary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSummaryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
