// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ReturnPingOKCode is the HTTP code returned for type ReturnPingOK
const ReturnPingOKCode int = 200

/*
ReturnPingOK OK message.

swagger:response returnPingOK
*/
type ReturnPingOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewReturnPingOK creates ReturnPingOK with default headers values
func NewReturnPingOK() *ReturnPingOK {

	return &ReturnPingOK{}
}

// WithPayload adds the payload to the return ping o k response
func (o *ReturnPingOK) WithPayload(payload string) *ReturnPingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the return ping o k response
func (o *ReturnPingOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReturnPingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
