// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReturnPingHandlerFunc turns a function with the right signature into a return ping handler
type ReturnPingHandlerFunc func(ReturnPingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReturnPingHandlerFunc) Handle(params ReturnPingParams) middleware.Responder {
	return fn(params)
}

// ReturnPingHandler interface for that can handle valid return ping params
type ReturnPingHandler interface {
	Handle(ReturnPingParams) middleware.Responder
}

// NewReturnPing creates a new http.Handler for the return ping operation
func NewReturnPing(ctx *middleware.Context, handler ReturnPingHandler) *ReturnPing {
	return &ReturnPing{Context: ctx, Handler: handler}
}

/*
	ReturnPing swagger:route GET / returnPing

ReturnPing return ping API
*/
type ReturnPing struct {
	Context *middleware.Context
	Handler ReturnPingHandler
}

func (o *ReturnPing) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewReturnPingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
